
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ID PV TIPO VIRG\nprograma : lista_declaracoes\n\nlista_declaracoes : lista_declaracoes declaracao\n                  | declaracao\n\ndeclaracao : TIPO lista_ids PV\n\nlista_ids : ID\n          | lista_ids VIRG ID\n'
    
_lr_action_items = {'TIPO':([0,2,3,5,8,],[4,4,-3,-2,-4,]),'$end':([1,2,3,5,8,],[0,-1,-3,-2,-4,]),'ID':([4,9,],[7,10,]),'PV':([6,7,10,],[8,-5,-6,]),'VIRG':([6,7,10,],[9,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'lista_declaracoes':([0,],[2,]),'declaracao':([0,2,],[3,5,]),'lista_ids':([4,],[6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> lista_declaracoes','programa',1,'p_programa','parser.py',9),
  ('lista_declaracoes -> lista_declaracoes declaracao','lista_declaracoes',2,'p_lista_declaracoes','parser.py',14),
  ('lista_declaracoes -> declaracao','lista_declaracoes',1,'p_lista_declaracoes','parser.py',15),
  ('declaracao -> TIPO lista_ids PV','declaracao',3,'p_declaracao','parser.py',20),
  ('lista_ids -> ID','lista_ids',1,'p_lista_ids','parser.py',28),
  ('lista_ids -> lista_ids VIRG ID','lista_ids',3,'p_lista_ids','parser.py',29),
]
